"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/base/header";
import Footer from "@/components/base/footer";
import { Provider } from "react-redux";
import { store } from "@/store/store";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Movie Review App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body
          className={`${inter.className} bg-primary text-zinc-900 min-h-screen custom-scrollbar`}
        >
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </Provider>
  );
}
